### ISSUE TITLE
Crash If collector is down

### ISSUE THREAD

**Issue by Payll** [INDEN-Intelligo/ProcessStorageUnit#3]
The module crashes if the collectors don't work (see for a try catch and the to make several try before giving up)

**Comment by lumi-git** [comment]
ERROR on colsole :

prod-unit_process-1  | 2023-03-23T10:09:46.513Z  INFO 42 --- [nio-8080-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
prod-unit_process-1  | 2023-03-23T10:09:46.513Z  INFO 42 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
prod-unit_process-1  | 2023-03-23T10:09:46.513Z  INFO 42 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 0 ms        
prod-unit_process-1  | java.net.ConnectException: Connection refused
prod-unit_process-1  |  at java.base/sun.nio.ch.Net.connect0(Native Method)
prod-unit_process-1  |  at java.base/sun.nio.ch.Net.connect(Net.java:579)
prod-unit_process-1  |  at java.base/sun.nio.ch.Net.connect(Net.java:568)
prod-unit_process-1  |  at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
prod-unit_process-1  |  at java.base/java.net.Socket.connect(Socket.java:633)
prod-unit_process-1  |  at java.base/java.net.Socket.connect(Socket.java:583)
prod-unit_process-1  |  at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
prod-unit_process-1  |  at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
prod-unit_process-1  |  at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
prod-unit_process-1  |  at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:279)
prod-unit_process-1  |  at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:384)
prod-unit_process-1  |  at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:406)
prod-unit_process-1  |  at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1309)
prod-unit_process-1  |  at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
prod-unit_process-1  |  at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
prod-unit_process-1  |  at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1057)
prod-unit_process-1  |  at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
prod-unit_process-1  |  at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
prod-unit_process-1  |  at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
prod-unit_process-1  |  at com.example.demo.DemoApplication.getMachin(DemoApplication.java:35)
prod-unit_process-1  |  at com.example.demo.DemoApplication.hello(DemoApplication.java:24)
prod-unit_process-1  |  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
prod-unit_process-1  |  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
prod-unit_process-1  |  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
prod-unit_process-1  |  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
prod-unit_process-1  |  at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207)
prod-unit_process-1  |  at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152)
prod-unit_process-1  |  at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
prod-unit_process-1  |  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884)
prod-unit_process-1  |  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
prod-unit_process-1  |  at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
prod-unit_process-1  |  at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081)
prod-unit_process-1  |  at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)
prod-unit_process-1  |  at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)
prod-unit_process-1  |  at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)
prod-unit_process-1  |  at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:705)
prod-unit_process-1  |  at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
prod-unit_process-1  |  at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:814)
prod-unit_process-1  |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:223)
prod-unit_process-1  |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
prod-unit_process-1  |  at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
prod-unit_process-1  |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
prod-unit_process-1  |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
prod-unit_process-1  |  at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
prod-unit_process-1  |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
prod-unit_process-1  |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
prod-unit_process-1  |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
prod-unit_process-1  |  at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
prod-unit_process-1  |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
prod-unit_process-1  |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
prod-unit_process-1  |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
prod-unit_process-1  |  at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
prod-unit_process-1  |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
prod-unit_process-1  |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
prod-unit_process-1  |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
prod-unit_process-1  |  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177)
prod-unit_process-1  |  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
prod-unit_process-1  |  at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
prod-unit_process-1  |  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:119)
prod-unit_process-1  |  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
prod-unit_process-1  |  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
prod-unit_process-1  |  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
prod-unit_process-1  |  at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:400)
prod-unit_process-1  |  at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
prod-unit_process-1  |  at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:859)
prod-unit_process-1  |  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1734)
prod-unit_process-1  |  at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
prod-unit_process-1  |  at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
prod-unit_process-1  |  at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
prod-unit_process-1  |  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
prod-unit_process-1  |  at java.base/java.lang.Thread.run(Thread.java:833)
